### ISSUE TITLE
ISBAT use SCRIPT_DEBUG mode with CoBlocks

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1160]
If a WordPress site has `SCRIPT_DEBUG` mode enabled CoBlocks will log errors related to missing assets. This is due to the development versions of scripts not being bundled with the released CoBlocks version. This behavior is sourced here: https://github.com/godaddy-wordpress/coblocks/blob/0f10970b4de2f1897ca845144decf97bea1bb979/class-coblocks.php#L141-L148

The exclusion of development scripts is sourced here: 
https://github.com/godaddy-wordpress/coblocks/blob/0f10970b4de2f1897ca845144decf97bea1bb979/gruntfile.js#L78-L89

CoBlocks should consider bundling development scripts for those who use `SCRIPT_DEBUG` mode or consider using different behavior when `SCRIPT_DEBUG` is enabled.

**Inspired with WordPress.org support request**
https://wordpress.org/support/topic/404-on-scripts-when-script_debug-set-to-true/

**Comment by rxnlabs** [comment]
Was just about to report this. Was wondering why none of the coblocks blocks worked on my staging site until I checked the console and saw some 404 errors when trying to load the coblock JS csripts

**Comment by stephenheron** [comment]
Yeah we just ran into this problem when on development. 

It would be good to include the development scripts I think.

**Comment by jrtashjian** [comment]
We are currently migrating our build process to utilize the `@wordpress/scripts` package and this issue will be resolved alongside it. Instead of using `SCRIPT_DEBUG` in our code and packaging two different scripts (increasing the payload) we are removing it entirely, only packaging the minified scripts. If developing with the source files from this repo, the full source files will be available to the developer. They will share the same name so that the `SCRIPT_DEBUG` constant is no longer needed.

**Comment by richtabor** [comment]
@jrtashjian Can we close this?

**Comment by jrtashjian** [comment]
Yes, this has been added in #1183 which we are preparing to merge soon.
