### ISSUE TITLE
ISBAT resize browser without masonry block images overlapping

### ISSUE THREAD

**Issue by p-jackson** [godaddy-wordpress/coblocks#1370]
### Describe the bug:

I should be able to resize the browser without masonry block images overlapping. At some browser sizes the images show superimposed on top of each other like the gutter between images hasn't been calculated properly.

After nudging the browser size a little more the alignment will be recalculated and show correctly.

I was able to reproduced the bug all the way back to v1.11.0 when the masonry block was introduced.

Also reported here Automattic/wp-calypso#39548

### To reproduce:

1. Add images to masonry gallery
2. Resize browser (can be done in editor, bug doesn't only happen on frontend)
3. Find a browser width at which images overlap (I was able to reproduce it easiest using mobile layout, but we have seen the issue at desktop width too)

### Expected behavior:

The correct gutter between images should be maintained as browser resizes (at least after the debounced relayout fires)

### Screenshots:

![masonry-gutter](https://user-images.githubusercontent.com/1500769/74892496-a7c13380-53ee-11ea-831e-34fa240cc304.gif)

View of block properties in case those are relevant
<img width="827" alt="properties" src="https://user-images.githubusercontent.com/1500769/74893099-629e0100-53f0-11ea-8f8a-9aad1436bdb0.png">

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active (tested in twenty twenty)
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.3.2

### Gutenberg version:

6.6

**Comment by tijosh** [comment]
+1 to this. The Masonry block is nearly unusable for mobile devices.

**Comment by richtabor** [comment]
Do you have an example site with this running again? I'm not getting the same behavior on our demo ([here](https://wpnux.godaddy.com/v2/?template=everett&lang=en_US)) of the Masonry block. Are you?

**Comment by tijosh** [comment]
@richtabor I can definitely try to set up a test site and see what I can find. 

FWIW, I'm able to repro this on the site you linked in Chrome dev tools device toolbar:

![Screenshot](https://d.pr/i/dAO2Uf+)

Although, that site looks ok in my actual mobile browsers. Will test more.

**Comment by hacchism** [comment]
Got a report from the user who owns https://myexplorationproject.com/.

The user is seeing a gallery like below when they see it via their iPhone 11(with Safari):

<img width="457" alt="Screen Shot 2020-07-19 at 10 26 13" src="https://user-images.githubusercontent.com/32432463/87865329-e57eb400-c9ae-11ea-83d1-222efd2558cc.png">

Although, it looks just fine with my iPhone XR(I guess it's because of the slight difference of screen width between 11 and XR).

Also, when I check the site in Chrome dev tool(with iPhone X mode), I can repro the issue as well:

<img width="383" alt="Screen Shot 2020-07-19 at 11 04 05" src="https://user-images.githubusercontent.com/32432463/87865380-971de500-c9af-11ea-9691-d597a32abd69.png">
