### ISSUE TITLE
ISNBAT see the icons style panel when custom icons are loaded and no config.json exists

### ISSUE THREAD

**Issue by colorful-tones** [godaddy-wordpress/coblocks#1405]
As an extension of the amazing work done on #1006 and #1403. If a user decides to add their own custom SVGs in a child theme _and_ chooses not to include an optional `config.json` to specify which icons are Filled vs Outlined. It would be nice to hide the Styles panel if their is no `config.json` otherwise it looks like this:

![Screenshot 2020-03-06 09 18 23](https://user-images.githubusercontent.com/405912/76092362-445a0880-5f8d-11ea-97bd-91c730114d3f.png)

**Comment by EvanHerman** [comment]
That's a good call. It makes sense to me. I'll take a look and see what we can do about hiding that panel in the event that:
- Default bundled icons are disabled
- Custom icons are loaded
- No `config.json` file is included in the custom icons directory

**Comment by EvanHerman** [comment]
@colorful-tones I've gone ahead and pushed up some changes back to #1403, since it was just easier to work off of that existing branch.

I think that things should just work as you intend when you pull down the latest changes. Essentially, when the default bundled icons are disabled and no `config.json` file exists in the custom config directory, the styles are unregistered causing the panel to not render.

Feel free to pull things down and give them a spin, and thank you for all of the great suggestions!

Evan
