### ISSUE TITLE
Gallery > Advanced > Spacing toggles are backwards

### ISSUE THREAD

**Issue by AlchemyUnited** [godaddy-wordpress/coblocks#1483]
### Describe the bug:
This is a UX bug. 

You toogle on to remove. And toggle off to add. That's counterintuitive.  That is, it's confusing. Kinda like speaking and using a double negative. 

It should be the other way around. 

- On "adds" space (or I suppose maintains the default)
- Off should remove the space 

p.s. Best I could tell, using those toggle had no visual effect on the actual admin blocks. This means that in order to know what the setting is the user has to focus the block and then open the Advanced settings panel. That's a long way to go for something that should be visually available regardless of block status; it shouldn't require those extra clicks.

**Comment by richtabor** [comment]
Thanks for the feedback @AlchemyUnited. I decided to go with that interaction because I needed this setting to be "off" by default, as not every block has these controls. You toggle the control to remove spacing (which is abnormal for blocks; not standard) - so you opt into the change. 

 It does affect the block, though if a theme overrides spacing - or there's been some changes in the editor which affect margin - it may be overridden.

**Comment by AlchemyUnited** [comment]
@richtabor - If off is the required default then adjust the verbiage to match. The double-negative / reverse-think is a UX violation.
