### ISSUE TITLE
Coblock styles not loading on archive pages.

### ISSUE THREAD

**Issue by frantorres** [godaddy-wordpress/coblocks#1490]
### Describe the bug:
Showing content that uses CoBlocks in a archive page doesn't shows the content correctly cause styles are not loaded. 

Looks like this would be linked to #1454 

### To reproduce:
1. Have content created with Gutenberg and CoBlocks in a post.
2. Editing your theme, load that content on at archive.php using some programming.
`$content = get_the_content(null, false, $postId);
if(!empty($content)){
    echo apply_filters( 'the_content', $content );
}`
3. The content appears, but CSS is not loaded.

### Expected behavior:
CoBlocks CSS to be loaded on pages where it is present, having in mind that it could be loaded in different circumstances than default behaviour. Or giving developers a way to override CSS optimisations. 

### Why
While Gutenberg is not available yet to create content to archive pages, I'm doing a custom linking to create content as post and show it as archive description.

### Isolating the problem:
- [x] This bug doesn't happen with 1.25.0 version.
- [x] This bug happens with 1.26.0 and 1.26.1 version.
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.3.2

**Comment by jrtashjian** [comment]
Hey @frantorres, thank you for submitting this issue! After diving into this issue deeper I believe this issue is stemming from how the `archive.php` template is being used.

The `archive.php` template is not meant to be used as a page template. It's a core template that is used if it exists in the theme directory for listing posts under a taxonomy, posts of a specific date, or list the site's authors. As soon as you use it as a page it triggers the `is_singular` condition and looks for blocks in the post content.

Although the bug here isn't related to #1454 exactly, it did help us to identify the various conditions needed to create #1511. Thank you again!
