### ISSUE TITLE
ISBAT - add image sizes on gallery-carousel

### ISSUE THREAD

**Issue by domegang** [godaddy-wordpress/coblocks#1524]
In my case, with responsive height enabled, the carousel is very very large.

From wp support forum, right now, there're 2 solutions.
1. upload smallest images, or resize them after upload.
2. Or some css tricks, but it doesn't solve my problem.

Could be useful to choose an image size on carousel gallery?
For example, the default wordpress sizes: thumbnail, medium, large, full.. or custom sizes?

Thanks

**Comment by jrtashjian** [comment]
Thanks @domegang for submitting this feature request!

I like this idea and have actually thought around how we'd implement it. Forcing one size over another isn't ideal so if we can add a control to allow the user to decide for their own application is useful. We can obviously set a sane default like "large" instead of "full" or maybe even add some custom sizes.

Alternatively, we could create these custom image sizes for CoBlocks blocks and maybe control the size used based on the style or options selected.

**Comment by domegang** [comment]
Hi @jrtashjian , using "large" size as default size, right now, could be a good starting point.
Could be useful to prevent big size images loading.
I'm not sure about new custom sizes for coblocks... too many files generated.
