### ISSUE TITLE
Error with Content Views

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/coblocks#1539]
This post uses Content Views Pro to pull in other posts; the bottom entry (green background) does not have the correct ‘rows’ layout set in co-blocks in the original post.

1. Go to https://bibba.com/bip/
2. See the green background rows

- [X] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

Suggested fix:

It can be correct by using this code in CV settings:
/* Fix coblocks layout not show correctly in view */
var $html = $(‘.wp-block-coblocks-row’).first().closest(‘html’);
if ($(‘#coblocks-frontend-css’).length === 0) {
$html.append(‘<link rel=”stylesheet” id=”coblocks-frontend-css” href=”https://bibba.com/wp-content/plugins/coblocks/dist/coblocks-style.css&#8221; type=”text/css” media=”all”>’);
}

WordPress.org thread: https://wordpress.org/support/topic/plugin-only-loads-its-style-in-the-single-post-page-error-with-content-views/

**Comment by richtabor** [comment]
This may be related to the way we load styles (how they're not available on _every_ page).

**Comment by jrtashjian** [comment]
We need to test if this is related to the styles loading and if a recent released (which included fixes to that) resolve this.

I'm assigning this to myself to look into.

**Comment by jrtashjian** [comment]
@richtabor this is actually related to the custom css that is injected onto a page for our Row block. Because these posts are being pulled into another page, the post meta that includes the CSS is not pulled in. There is nothing we can effectively do about this. I'm going to close this as a won't fix for this reason and also because we want to migrate our Row block to the core Columns block in the future.

@PavleMarjanovic I would suggest using the Columns block included with WordPress over the CoBlocks one if they need this functionality.
