### ISSUE TITLE
ISBAT insert Pricing Table block without breaking the inserter

### ISSUE THREAD

**Issue by WunderBart** [godaddy-wordpress/coblocks#1634]
### Describe the bug:
Inserting the Pricing Table block via the main inserter sets the inserter in a weird state. It ends up searching Block Directory for the current search term while displaying only the unclickable Pricing Table item. Fortunately, this can be fixed by re-opening the inserter so the severity is low.

### To reproduce:

1. Go to the editor
2. Open the main block inserter
3. Search for the Pricing Table block and click it
4. The block should be inserted correctly but the inserter should end up in a broken state (described above).

### Expected behavior:
When clicking to insert the Pricing Table block, the inserter should behave as it would for any other block - remain in the current state.

### Screenshots:

![coblocks pricing table bug](https://user-images.githubusercontent.com/1451471/90763219-95b14680-e2e6-11ea-8715-3f59443522d6.gif)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
  ⚠️ It doesn't happen with the Gutenberg version included in the WP 5.5 - I only tested it with 8.7.1. The biggest difference between those 2 versions is the Block Directory - it's not available with the Gutenberg included in 5.5.
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.5

### Gutenberg version:
8.7.1

**Comment by richtabor** [comment]
Hey @WunderBart, I think there's a misunderstanding as this is normal behavior.

The Pricing Table block allows one block, the Pricing Table Item block, of which its child blocks are limited to the blocks initially added. As that block is selected, there are no blocks to add inside of it. 

The difference, as you indicated, is that the block directory forces that window to stay open - whereas in WP 5.5, it is auto-closed because there are no actions to be taken.
