### ISSUE TITLE
ISBAT use the Code Editor without seeing class names duplicated

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/coblocks#1879]
### Describe the bug:
When I have CoBlocks enabled I can’t use the Code Editor without seeing class names being duplicated rapidly. Also noticed some problem with the Media-Text Block after disabling/re-enabling the CoBlocks plugin, the has-animation class caused them all to have opacity 0 but no actual animation, I guess they lost their animation settings after toggle but they kept the classes as custom classes.

### To reproduce:

Happens on other objects too I think like columns.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7

**Comment by AnthonyLedesma** [comment]
Hi @PavleMarjanovic, Thank you for taking the time to make this issue. Recently this issue was reported https://github.com/godaddy-wordpress/coblocks/issues/1862 and a PR was merged with a fix for this behavior with the Group block.  Are you able to replicate this behavior with other blocks?

We also have the latest CoBlocks changes available to test against the repeating class names which you can download here: https://github.com/godaddy-wordpress/coblocks/releases/download/canary/coblocks-canary.zip

We hope to get a release with this fix out today.

**Comment by AnthonyLedesma** [comment]
Tested today with 2.14.1 against the Media and Text block as well as the Group and Column blocks and cannot replicate. Closing this issue.
