### ISSUE TITLE
ISBAT Offset feature for the Posts block

### ISSUE THREAD

**Issue by mvlaisavljevic** [godaddy-wordpress/coblocks#1880]
### Is your feature request related to a problem? Please describe.
No, this would be an additional feature.

### Describe the solution you'd like
It would be great if we could extend the Posts block by adding an offset option.

https://wordpress.org/support/topic/shortcode-support-40/

**Comment by AnthonyLedesma** [comment]
The offset feature is not a feature that we will be introducing to the Posts or Post Carousel blocks. Instead, we have implemented logic to hide the current post from the Posts and Post Carousel blocks. This change thereby offsets the posts and accomplishes the ask automatically. Closing this issue as fixed with CoBlocks V2.14.1
