### ISSUE TITLE
ISBAT see my selected colors used within the Quote block caption

### ISSUE THREAD

**Issue by ehamwey** [godaddy-wordpress/coblocks#1912]
### Describe the bug:
Currently, the Quote block does not allow for the caption colors to be changed. Changing the Text color, regardless of what text is selected, only changes the heading color, not the caption color. Additionally, when applying Text color from the toolbar menu, color selection breaks entirely. 

### To reproduce:
1. Add a Quote block
2. Add a caption and select it
3. Attempt to apply text color

### Expected behavior:
Caption text color changes or the Inspector pane should not be visible

### Screenshots:
![Untitled](https://user-images.githubusercontent.com/9936886/120675501-21a1f280-c463-11eb-8b65-8237da91c877.gif)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7.2

**Comment by AnthonyLedesma** [comment]
Color controls do not exist for Quote block by default. These controls are being extended by CoBlocks.

**Comment by snovosel** [comment]
After digging into this in depth, I'm not sure if this is something that is being caused by CoBlocks. Looking at the Quote block within Gutenberg, the block itself is receiving the correct attributes ( a `style` object prop with the key `color` ), however it is simply spreading this object to a `blockquote` html element, not a react component. The `blockquote` element requires a sub child style to be set , ie:

```
blockquote > p {
     color: #ffffff
}
```
and so inline styles will not be applied to the child p tag. 

I've linked some info on the core/quote block source code and its underlying `<BlockQuotation>` child for visibility: 

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/quote/edit.js#L50

https://github.com/WordPress/gutenberg/tree/trunk/packages/primitives/src/block-quotation

**Comment by snovosel** [comment]
After reviewing in more detail adding a `color: inherit !important` property via a stylesheet allows for the block p tag to inherit the colors being injected into the block quote element
