### ISSUE TITLE
ISBAT have my theme.json content widths respected

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/coblocks#1935]
### Describe the bug:
CoBlocks affect the content sizing.

### Expected behavior:
https://drive.google.com/file/d/15O-IjDQ6CDhqkeVO3HbBb5fCx56LD7-3/view

### Screenshots:
https://drive.google.com/file/d/15O-IjDQ6CDhqkeVO3HbBb5fCx56LD7-3/view

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
WordPress 5.8

**Comment by ndiego** [comment]
I can elaborate on this since I was the one that originally posted the issue on WordPress.org. When CoBlocks in activated along with the Gutenberg plugin and a block-based theme, the content widths are not respected in the block editor. 

To replicate:

1. Create a fresh WordPress install and install the lastest versions of CoBlocks, Gutenberg and a block-based theme. I used TT1 Blocks which is available in the repo. 
2. Activate Gutenberg and TT1 Blocks. 
3. Open any page/post and see that the content widths that are set in the theme.json file are respected in the editor. 
4. Then activate CoBlocks. 
5. Go back to the page/post and refresh. Now the content widths are no longer respected. (Note this issue does not impact the frontend, only the editor)

Hopefully that is helpful in diagnosing the cause. Let me know if I can answer any additional questions.
