### ISSUE TITLE
Child plugin : Add functionality, blocks or styles to CoBlocks ( hook, filter )

### ISSUE THREAD

**Issue by Wewill** [godaddy-wordpress/coblocks#1940]
Is that a way to add features to CoBlocks without losing updates ? 
For exemple, for a project, I needed multiples alerts colors styles : I added it, and rebuild plugin. It's easy, but, now I'll need to do a diff and merge for all next updates, and rebuild plugin. 

Is there a way to make a child plugin, or can you add powerful hooks and filters ? 

Thanks for your reply ! 

e.g. 

![Capture d’écran 2021-07-19 à 14 48 07](https://user-images.githubusercontent.com/3178443/126162207-6361b413-70c5-41e1-9174-280c90c6a943.png)

**Comment by AnthonyLedesma** [comment]
Instead of making a child plugin for CoBlocks, I would instead advise creating your own plugin that might modify CoBlocks assets. They could work together in that way but CoBlocks would essentially be the original un-modified version and your custom plugin would extend what is needed. Just to give a quick example we extend Core blocks like the Cover block by adding additional styles. I would recommend attempting to extend CoBlocks blocks in the same way.
https://github.com/godaddy-wordpress/coblocks/blob/3b04c953ad50ed16f0c39706ef6f271d612fd9de/src/extensions/cover-styles/index.js#L15-L27

**Example in the editor**
![image](https://user-images.githubusercontent.com/30462574/126199321-bb127354-e47f-49b2-a8c3-84bf1f651ec6.png)

I hope this helps.

**Comment by Wewill** [comment]
Hi @AnthonyLedesma, 

Thank you for your reply, it helps me a lot !

I ok with the plugin, but still not comfortable with ES6 / Gutemberg ; do you recommand a starter plugin or do you know a good tutorial about ? It have to be build right ? 

Thanks a lot.

**Comment by AnthonyLedesma** [comment]
Hi @Wewill,

WordPress now provides a guide here: https://developer.wordpress.org/block-editor/how-to-guides/javascript/js-build-setup/.

The guide covers initial setup, configuration, and a lot of explanation. I think using these steps you could generate a simple JavaScript Gutenberg plugin for WordPress. Besides this guide I know there are a whole lot more out there on the internet. While looking for this guide I stumbled across several YouTube tutorials as well.

**Comment by Wewill** [comment]
Thank you @AnthonyLedesma !
