### ISSUE TITLE
ISNBAT enable invisible block states with `coblocks-animate` class

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1941]
### Describe the bug:

Discovered in https://github.com/godaddy-wordpress/coblocks/issues/1879 but not officially reported is a situation where the Media and Text block is able to enter an unusable state. This can only happen when the CoBlocks plugin is disabled and re-enabled later. While perhaps not a typical user interaction, the enabling and disabling of common plugins are steps that many developers take when simply troubleshooting website issues. It is reasonable to believe this situation could happen in the wild and should be handled as a sort of deprecation hopefully.

This behavior occurs with the 'core/media-text' 'core/image' 'core/group' 'core/gallery' 'core/cover' and 'core/columns' blocks.

### To reproduce:

1. Create new post and add the Media and Text block.
2. Edit the Media and Text block to have an image and enable any of the animation control settings.
3. Save post.
4. Using WP-CLI we first disable CoBlocks. `wp plugin deactivate coblocks`
5. Reload post and notice (expected) block error. Attempt block recovery. Save post.
6. Using WP-CLI we activate CoBlocks. `wp plugin active coblocks`
7. Reload post and notice that Media and Text are hidden with `opacity: 0`.
8. Notice that attributes are not parsed due to user interaction to Attempt block recovery.

### Expected behavior:

This interaction is a complicated one but the UX impact is quite large with hidden blocks in the editor.

### Screenshots:

![image](https://user-images.githubusercontent.com/30462574/126204446-25f61165-7c94-4b19-921e-992c16dd7d79.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.7.2

### Gutenberg version:

N/A

**Comment by snovosel-godaddy** [comment]
@AnthonyLedesma I was able to determine that this is happening because of the className `coblocks-animate` being saved to the block attributes without the animation attribute being saved (after block recovery). I added a filter to remove this class if the attributes has an undefined animation set. This will fail block validation but the 0 opacity will not be set by way of the `coblocks-animate` class and following block recovery the block will display as normal (without a set animation)

[PR can be found here](https://github.com/godaddy-wordpress/coblocks/pull/1968)
