### ISSUE TITLE
FontSizePicker not working properly after WordPress 5.8 update

### ISSUE THREAD

**Issue by NasKadir123** [godaddy-wordpress/coblocks#1945]
### Describe the bug:
After WordPress update to 5.8, when try to change the font size of your custom blocks it shows that the content is unexpected

### To reproduce:
For example, create the author block and type something, then try to change font size, then update the page and refresh it.

### Expected behavior:
I expect no crashes after font size change. I think the problem appeared because of the new additional unit sizes for Font Size picker.

### Screenshots:
https://prnt.sc/1e2iaph, https://prnt.sc/1e2iokg

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
WordPress 5.8

### Gutenberg version:
Gutenberg 10.7

**Comment by NasKadir123** [comment]
What I see is that FontSizePicker doesn't support value as a 'number', because in the 10.7 version FontSizePicker has px, em and rem units...

**Comment by AnthonyLedesma** [comment]
Thank you for bringing this to our attention @NasKadir123. It turns out that there is a [bug in WordPress 5.8 with the shared components that we use to control the font sizes](https://github.com/WordPress/gutenberg/issues/33653). 


We hope to have a [fix released soon](https://github.com/godaddy-wordpress/coblocks/pull/1949) that will allow proper use of the font size controls.
