### ISSUE TITLE
Custom font controls only for administrators

### ISSUE THREAD

**Issue by Tilmn** [godaddy-wordpress/coblocks#2103]
### Describe the bug:
`Authors` should be able to change the custom font settings introduced by CoBlocks. But only `Administrators` see them.

### To reproduce:
1. Create a new post
2. Type some text so a paragraph block is created
3. Select the text
4. If you are a user with the role `Administrator` you see a custom font control icon in the popup. If you are a user with a different role, there is only the standard settings available.

### Expected behavior:
Custom font controls should be available to anybody who can edit a post or a page, not just administrators.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress themes active (Twenty Twenty, Twenty Twenty-One)
- [x] I can reproduce this bug consistently using the steps above

### Versions
WordPress version 5.8.1
CoBlocks Plugin version 2.17.0

**Comment by fjarrett-godaddy** [comment]
I agree, this is a good suggestion. Since roles are customizable, I think that any user with the `edit_posts` capability should be allowed to modify fonts on a post. And by default, this would include Contributors as well as Authors.

https://wordpress.org/support/article/roles-and-capabilities/#edit_posts
