### ISSUE TITLE
ISBAT add custom icons or choose from larger selection of Icons

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#923]
**Is your feature request related to a problem? Please describe.**
The Icon block has great functionalities with the ability to resize and set custom colors. The block could be improved if a user had an easy way to add custom icons. If not adding custom icons, perhaps we should explore expanding the selection of available Scalable Vector Graphics to use as icons.

**Describe alternatives you've considered**
Alternatives to additional icons would be to use a regular image with Image block or to use SVG markup within an HTML block. The negative with this alternative is that the user cannot set custom colors easily and cannot adjust the size in a scalable way.

**Additional context**
A few ideas for additional icons.
- Sports (championship, teams, people etc.)
- Brands (Google, Facebook, Amazon, Microsoft etc.)
- Animals
- Emojis (emotions)
- Places (Eiffel Tower, Pyramids etc.) 

**Inspired by WordPress.org support requests.**
https://wordpress.org/support/topic/icon-block/
https://wordpress.org/support/topic/icon-block-2/

**Comment by richtabor** [comment]
We could certainly add more icons to the current Icon block, though I don't think we should look into user-uploaded icons just yet. Gutenberg is [working on an Icon block](https://github.com/WordPress/gutenberg/issues/16484) that will have this functionality, so I'd like to see what happens there first - instead of duplicating efforts.
